// Modified from app/layout.js - the root app layout
import './globals.css'
import { Inter } from 'next/font/google' // supports google fonts
import NavBar from '../components/NavBar'
import { Footer } from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

// Exported metadata will appear in the <head> section
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// All layouts support nesting via children prop
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}